### ISSUE TITLE
你好啊，piCore不是才8.3版本吗？这个已经是9了？

### ISSUE THREAD

**Issue by edison99x** [kisChang/piCore#1]
你好啊，piCore不是才8.3版本吗？这个已经是9了？

**Comment by edison99x** [comment]
不知能否集成tidal connect？

**Comment by kisChang** [comment]
现在已经13.1了...
可以上官网看一下：http://forum.tinycorelinux.net/index.php/board,72.0.html   
不知道能否集成tidal connect，我没接触过这个软件

**Comment by edison99x** [comment]
https://docs.picoreplayer.org/releases/pcp800/
哈哈，我指的是这个picoreplayer 8.0，他是基于picore 13的播放器



Cheng-wei Chen

Department of Cerebrovascular Surgery

The Third Affiliated Hospital, Sun Yat-Sen Universit

发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月23日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [kisChang/piCore] 你好啊，piCore不是才8.3版本吗？这个已经是9了？ (Issue #1) |

现在已经13.1了...
可以上官网看一下：http://forum.tinycorelinux.net/index.php/board,72.0.html
不知道能否集成tidal connect，我没接触过这个软件

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kisChang** [comment]
搞错了🤣
